# Dependencies
markdown: kramdown
highlighter: pygments

# Permalinks
permalink: pretty
relative_permalinks: false

# Setup
title: Daniel's Blog
tagline: "Home of my programs"
description: "Welcome to my programming blog! I have plenty of posts about my programming (and some non-programming) achievements."
url: http://hyde.getpoole.com
baseurl: /

author:
  name: "Daniel Yang"
  url: https://twitter.com/Daniel_Yanger

plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

paginate: 1

# Custom vars
version: 2.1.0

github:
  repo: https://github.com/DanielYanger
